### ISSUE TITLE
Should Qubit::Fixed be usize?

### ISSUE THREAD

**Issue by notmgsk** [rigetti/quil-rust#8]
`Qubit::Fixed` is synonymous with an _index_, and so it is to be expected that they will be used as such (an index into an array). This is an issue now because `Qubit::Fixed` is `u64` which must be converted into a `usize` so that it can be used to index an array. That's usually fine because most of us have 64bit computers and so `u64` wouldn't be truncated. But it might be polite (and cleaner, in my experience -- no more `index as usize`) to define them as `usize`.

WDYT?

**Comment by genos** [comment]
I'm a fan @notmgsk; lean on the type system a bit more, since to me `usize` says "I'm used as a size or index."

**Comment by genos** [comment]
PR attempt in #17, though y'all should feel free to cast it into the fire if you don't like it.

**Comment by kalzoo** [comment]
I'm not sure - `usize` is useful because it expresses a size corresponding to the target architecture...but in this case it represents a size corresponding to the _compiler's_ architecture. Should more qubits or longer memory references be available to a Quil program, executed on the same hardware, when compiled on a 64-bit system than 32-bit?

I agree that `u64 as usize` should be avoided when able. I could see this working.

**Comment by genos** [comment]
Point well taken! Much as I like using `usize` for an index or length, having the bit length specified arch-agnostically seems a good idea. Does the language spec define the necessary integral size? And I don’t think I saw any `as` casting in my editing, so I may be swinging at shadows here anyway. I’ll kill #17 for now, and should we want we can revisit some other time.

**Comment by kalzoo** [comment]
Going to close this for now. My assumption with Quil is that bit depth is unspecified and left to the compiler. I think it's fair to specify `u64`/`f64` for literal integers and real values respectively within our own compiler, returning errors on overflow.
